// Generated by ts-to-zod (https://www.npmjs.com/package/ts-to-zod)
import { z } from "zod";
import { registry } from "../../../docs/openApi";

export const categoryCrudApiModelSchema = z.object({
    id: z.string(),
    name: z.string(),
    active: z.boolean(),
    color: z.string().optional(),
    icon: z.string().optional()
}).openapi({
    type: "object",
    example: {
      id: "123",
      name: "Category 1",
      active: true,
      color: "red",
      icon: "fa-solid fa-circle",
    },
  });

registry.register('categoryCrudApiModel', categoryCrudApiModelSchema);