// Generated by ts-to-zod
import { z } from "zod";
import { registry } from "../../docs/openApi";

export const userApiModelSchema = z
  .object({
    id: z.string(),
    name: z.string(),
    email: z.string().nullable(),
    token: z.string().nullable(),
    roles: z.array(z.string()),
  })
  .openapi({
    type: "object",
    example: {
      id: "123",
      name: "John Doe",
      email: "john@example.com",
      token: "abc123",
      roles: ["ADMIN", "MANAGER"],
    },
  });


registry.register('userApiModel', userApiModelSchema);