// Generated by ts-to-zod (https://www.npmjs.com/package/ts-to-zod)
import { z } from "zod";

export const paymentMethodCrudApiModelSchema = z.object({
    id: z.number(),
    name: z.string(),
    active: z.boolean(),
    color: z.string(),
    icon: z.string()
});
