// Generated by ts-to-zod (https://www.npmjs.com/package/ts-to-zod)
//Some schemas can't be generated due to direct or indirect missing dependencies:
//paymentCrudApiModelSchema
//paymentApiModelSchema
import { Decimal } from "@prisma/client/runtime/library";
import { z } from "zod";
import { registry } from "../../docs/openApi";

export const paymentCrudApiModelSchema = z.object({
    id: z.string(),
    amount: z.number().transform((val) => new Decimal(val)),
    reference: z.string(),
    paymentMethodId: z.number(),
    orderId: z.string()
}).openapi({
    type: "object",
    example: {
      id: "123",
      amount: 100,
      reference: "123456789",
      paymentMethodId: 1,
      orderId: "123",
    },
  });

export const paymentApiModelSchema = z.object({
    id: z.string(),
    amount: z.number().transform((val) => new Decimal(val)),
    reference: z.string(),
    paymentMethodId: z.number(),
    orderId: z.string()
}).openapi({
    type: "object",
    example: {
      id: "123",
      amount: 100,
      reference: "123456789",
      paymentMethodId: 1,
      orderId: "123",
    },
  });

registry.register('paymentCrudApiModel', paymentCrudApiModelSchema);
registry.register('paymentApiModel', paymentApiModelSchema);