// Generated by ts-to-zod (https://www.npmjs.com/package/ts-to-zod)
import { z } from "zod";
import { registry } from "../docs/openApi";

export const baseFilterSchema = z.object({
    pageNumber: z.number().optional(),
    pageSize: z.number().optional(),
    orderBy: z.union([z.literal("asc"), z.literal("desc")]).optional(),
    search: z.string().optional()
}).openapi({
    type: "object",
    example: {
      pageNumber: 1,
      pageSize: 10,
      orderBy: "asc",
      search: "product",
    },
  });

// inferred types:
export type BaseFilter = z.infer<typeof baseFilterSchema>;

registry.register('baseFilter', baseFilterSchema);