// Generated by ts-to-zod (https://www.npmjs.com/package/ts-to-zod)
//Some schemas can't be generated due to direct or indirect missing dependencies:
//productFilterBasicSchema

import { z } from "zod";
import { baseFilterSchema } from "../BaseFilter.schema";
import { registry } from "../../../apps/zasnode/src/docs/openApi";

export const productFilterBasicSchema = baseFilterSchema.extend({
    name: z.string().optional(),
    active: z.boolean().optional(),
    categoryIds: z.array(z.string()).optional()
}).openapi({
    type: "object",
    example: {
      pageNumber: 1,
      pageSize: 10,
      orderBy: "asc",
      search: "product",
      name: "Product 1",
      active: true,
      categoryIds: ["123", "456"],
    },
  });


  registry.register('productFilterBasic', productFilterBasicSchema);