// Generated by ts-to-zod (https://www.npmjs.com/package/ts-to-zod)
import { z } from "zod";
import { registry } from "../../docs/openApi";

export const createProductApiModelSchema = z.object({
    id: z.string(),
    name: z.string(),
    salePrice: z.number(),
    priceBase: z.number(),
    margin: z.number(),
    marginPercent: z.number(),
    active: z.boolean(),
    image: z.string().nullable(),
    description: z.string().nullable(),
    categoryIds: z.array(z.string())
}).openapi({
    type: "object",
    example: {
      id: "123",
      name: "Product 1",
      salePrice: 100,
      priceBase: 100,
      margin: 10,
      marginPercent: 10,
      active: true,
      image: "https://example.com/image.jpg",
      description: "This is a product description",
      categoryIds: ["123", "456"],
    },
  });

  registry.register('createProductApiModel', createProductApiModelSchema);