// Generated by ts-to-zod (https://www.npmjs.com/package/ts-to-zod)
//Some schemas can't be generated due to direct or indirect missing dependencies:
//productApiModelSchema

import { Decimal } from "@prisma/client/runtime/library";
import { z } from "zod";
import { registry } from "../../docs/openApi";

export const productApiModelSchema = z.object({
    id: z.string(),
    name: z.string(),
    salePrice: z.number().transform((val) => new Decimal(val)),
    priceBase: z.number().transform((val) => new Decimal(val)),
    margin: z.number().transform((val) => new Decimal(val)),
    marginPercent: z.number().transform((val) => new Decimal(val)),
    active: z.boolean(),
    image: z.string().nullable(),
    description: z.string().nullable()
}).openapi({
    type: "object",
    example: {
      id: "123",
      name: "Product 1",
      salePrice: 100,
      priceBase: 100,
      margin: 10,
      marginPercent: 10,
      active: true,
      image: "https://example.com/image.jpg",
      description: "This is a product description",
    },
  });

  registry.register('productApiModel', productApiModelSchema);