// Generated by ts-to-zod (https://www.npmjs.com/package/ts-to-zod)
import { z } from "zod";
import { registry } from "../../docs/openApi";

export const customerCrudApiModelSchema = z
  .object({
    id: z.string(),
    name: z.string(),
    surname: z.string(),
    identityValue: z.string(),
    address: z.string(),
    phone: z.string(),
    email: z.string(),
  })
  .openapi({
    type: "object",
    example: {
      id: "123",
      name: "John Doe",
      surname: "Doe",
      identityValue: "123456789",
      address: "123 Main St",
      phone: "555-123-4567",
      email: "john@example.com",
    },
  });

export const customerApiModelSchema = z
  .object({
    id: z.string(),
    name: z.string(),
    surname: z.string(),
    identityValue: z.string(),
    address: z.string(),
    phone: z.string(),
    email: z.string(),
  })
  .openapi({
    type: "object",
    example: {
      id: "123",
      name: "John Doe",
      surname: "Doe",
      identityValue: "123456789",
      address: "123 Main St",
      phone: "555-123-4567",
      email: "john@example.com",
    },
  });

// inferred types:
export type CustomerCrudApiModel = z.infer<typeof customerCrudApiModelSchema>;

export type CustomerApiModel = z.infer<typeof customerApiModelSchema>;

registry.register('customerCrudApiModel', customerCrudApiModelSchema);
registry.register('customerApiModel', customerApiModelSchema);